Docs: avoid doc test error when unsafe-vars are not enabled
'cargo test --doc' would fail:
---- src/slab.rs - slab::ParseSlab (line 164) stdout ----
error[E0599]: no method named `add_unsafe_var` found for struct `ParseSlab` in the current scope
  --> src/slab.rs:173:26
   |
11 |     unsafe { slab_mut.ps.add_unsafe_var("bad".to_string(), &bad); }  // `add_unsafe_var()` only exists if the `un...
   |                          ^^^^^^^^^^^^^^ method not found in `ParseSlab`
...

I checked that with the doc comment added, 'cargo test --doc' and
'cargo test --doc --features unsafe-vars' passes, the doc output looks unchanged,
and then when an error is introduced in the docs (e.g. a typo), they fail as
expected with '--features unsafe-vars'.